name: Generate Snake

# Controls when the action will run
on:
  schedule:
      # every 12 hours
    - cron: "0 */12 * * *"
  
  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:
  
  # Also run on every push to the main branch
  push:
    branches:
    - main
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: rootx90
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: output
          message: 'Generate Snake'
